language: minimal
dist: trusty
sudo: required
env:
- TEMPLATE=centos-ruby/7
- TEMPLATE=gce-parity/14.04
- TEMPLATE=gce-parity/16.04
- TEMPLATE=gce-parity/16.04-ppc64le
- TEMPLATE=ubuntu-ruby/14.04
- TEMPLATE=ubuntu-ruby/16.04
- TEMPLATE=ubuntu-systemd/16.04
- TEMPLATE=ubuntu-systemd/16.04-ppc64le
- TEMPLATE=ubuntu-upstart/12.04
- TEMPLATE=ubuntu-upstart/14.04
script:
- export DOCKER_DEST="travisci/${TEMPLATE//\//:}"
- echo "DOCKER_DEST=${DOCKER_DEST}"
- cd "${TEMPLATE}"
- docker build -t "${DOCKER_DEST}" .
after_success:
- cd "${TRAVIS_BUILD_DIR}"
- if [[ "${TRAVIS_BRANCH}" == 'master' && "${TRAVIS_PULL_REQUEST}" == 'false' ]]; then
    bin/docker-push;
  else
    echo "Not pushing.";
    echo "  TRAVIS_BRANCH=${TRAVIS_BRANCH}";
    echo "  TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}";
  fi
