language: bash
dist: trusty
sudo: required
env:
- TEMPLATE=centos-ruby/7
- TEMPLATE=gce-parity/14.04
- TEMPLATE=gce-parity/16.04
- TEMPLATE=ubuntu-ruby/14.04
- TEMPLATE=ubuntu-ruby/16.04
- TEMPLATE=ubuntu-systemd/16.04
- TEMPLATE=ubuntu-upstart/12.04
- TEMPLATE=ubuntu-upstart/14.04
matrix:
  include:
  - env: TEMPLATE=gce-parity/16.04-ppc64le
    os: power
  - env: TEMPLATE=ubuntu-systemd/16.04-ppc64le
    os: power
  allow_failures:
  - os: power
script: ./bin/docker-build
after_success: ./bin/docker-push
